```{r}
library(tidyverse)
rm(list = ls())#Clears environment variables
```


Reads in the .csv file which has already been added to the project folder
```{r}
ONP_Original <- read.csv(file = 'OnlineNewsPopularity.csv')
```

Removed Unnecessary Columns
```{r}
#ONP_Trimmed <- ONP_Original%>%select(-2:-3,-5:-7,-12:-13,-20:-28,-40:-44)
ONP_Trimmed <- ONP_Original%>%select(-2:-3,-5:-9,-12:-13,-20:-28,-40:-44)
```


```{r}
ONP_Business <- ONP_Trimmed%>%subset(data_channel_is_bus == 1)
```

created histogram to show avg number of shares
```{r}
hist(ONP_Trimmed$self_reference_avg_sharess)
```

histogram to visualize number of words in the articles 
```{r}
hist(ONP_Trimmed$n_tokens_content)
```
```{r}
sapply(ONP_Trimmed, function(x) sum(is.na(x)))
```

```{r}
ONP.lm = lm(formula=shares ~ num_videos + num_imgs + n_tokens_content + rate_positive_words+rate_negative_words, data = ONP_Trimmed)
summary(ONP.lm)
```
```{r}
# ONP.glm = glm(formula=shares ~ num_videos + num_imgs + n_tokens_content + rate_positive_words+rate_negative_words, data = ONP_Trimmed)
# summary(ONP.glm)
# pred_ONP <- predict(ONP.lm, type="response")
# pred_ONP
```
```{r}
#both solutions I have found do the same thing which is treat the variable as a factor. Either by changing it to a factor before running the model or buy specifying that you want that variable treated as a factor in the model. 

#ONP_Trimmed$is_weekend = as.factor(ONP_Trimmed$is_weekend)#I am not sure if this is working correctly but I read that as long as the variable is a factor, R will know it is being looked at categorically 

#code tested as factor
ONP.lm = lm(formula=shares ~ num_videos + num_imgs + n_tokens_content + rate_positive_words+rate_negative_words+factor(weekday_is_saturday), data = ONP_Trimmed)
summary(ONP.lm)

#code tested as binary(original)
ONP.lm2 = lm(formula=shares ~ num_videos + num_imgs + n_tokens_content + rate_positive_words+rate_negative_words+weekday_is_saturday, data = ONP_Trimmed)
summary(ONP.lm2)

#code tested using Kellen's method with saturday replacing the 1's
ONP_Trimmed$weekday_is_saturday <- ONP_Trimmed$weekday_is_saturday%>%replace(ONP_Trimmed$weekday_is_saturday==1, "Saturday")

ONP.lm3 = lm(formula=shares ~ num_videos + num_imgs + n_tokens_content + rate_positive_words+rate_negative_words+weekday_is_saturday, data = ONP_Trimmed)
summary(ONP.lm3)
#all three models produced he same result for saturday column
```


```{r}
ggplot(ONP_Trimmed,aes(num_videos,shares) ) + geom_col(size = 5, alpha = 0.5, color="red")
```
```{r}
ggplot(ONP_Trimmed, aes(num_imgs,shares)) + geom_col(size = 3, colour = "blue",  )
```

lm model with all the variables to see effect on shares
```{r}
set.seed(111)
trainList <- createDataPartition(y=ONP_Trimmed$shares, p=.80,list=F)
trainSet <- ONP_Trimmed[trainList,]
testSet <- ONP_Trimmed[-trainList,]
fit1 <- lm(shares ~., trainSet)

#don't run, still need to tweak. 
```


```{r}
onptest <- ONP_Trimmed

pubday <- onptest%>%select(weekday_is_monday:weekday_is_sunday)

pubday$weekday_is_monday <- pubday$weekday_is_monday%>%replace(pubday$weekday_is_monday==1, "Monday")

pubday$weekday_is_tuesday <- pubday$weekday_is_tuesday%>%replace(pubday$weekday_is_tuesday==1, "Tuesday")

pubday$weekday_is_wednesday <- pubday$weekday_is_wednesday%>%replace(pubday$weekday_is_wednesday==1, "Wednesday")

pubday$weekday_is_thursday <- pubday$weekday_is_thursday%>%replace(pubday$weekday_is_thursday==1, "Thursday")

pubday$weekday_is_friday <- pubday$weekday_is_friday%>%replace(pubday$weekday_is_friday==1, "Friday")

pubday$weekday_is_saturday <- pubday$weekday_is_saturday%>%replace(pubday$weekday_is_saturday==1, "Saturday")

pubday$weekday_is_sunday <- pubday$weekday_is_sunday%>%replace(pubday$weekday_is_sunday==1, "Sunday")


pubday2 <- pubday%>%unite(weekday_is_monday:weekday_is_sunday, col = "day of week", remove = T, sep ="_" )

pubday2$`day of week` <- gsub("_", "", pubday2$`day of week`)
pubday2$`day of week` <- gsub("0", "", pubday2$`day of week`)
#have issue with _0_ being included in the main merged column.. 




```

```{r}
ONP_Test <- ONP_Trimmed

ONP_Test$weekday_is_monday <- ONP_Test$weekday_is_monday%>%replace(ONP_Test$weekday_is_monday==1, "Monday")

ONP_Test$weekday_is_tuesday <- ONP_Test$weekday_is_tuesday%>%replace(ONP_Test$weekday_is_tuesday==1, "Tuesday")

ONP_Test$weekday_is_wednesday <- ONP_Test$weekday_is_wednesday%>%replace(ONP_Test$weekday_is_wednesday==1, "Wednesday")

ONP_Test$weekday_is_thursday <- ONP_Test$weekday_is_thursday%>%replace(ONP_Test$weekday_is_thursday==1, "Thursday")

ONP_Test$weekday_is_friday <- ONP_Test$weekday_is_friday%>%replace(ONP_Test$weekday_is_friday==1, "Friday")

ONP_Test$weekday_is_saturday <- ONP_Test$weekday_is_saturday%>%replace(ONP_Test$weekday_is_saturday==1, "Saturday")

ONP_Test$weekday_is_sunday <- ONP_Test$weekday_is_sunday%>%replace(ONP_Test$weekday_is_sunday==1, "Sunday")


ONP_Test <- ONP_Test%>%unite(weekday_is_monday:weekday_is_sunday, col = "day of week", remove = T, sep ="_" )

ONP_Test$`day of week` <- gsub("_", "",ONP_Test$`day of week`)
ONP_Test$`day of week` <- gsub("0", "", ONP_Test$`day of week`)

ONP.lm4 = lm(formula=shares ~ num_videos + num_imgs + n_tokens_content + rate_positive_words+rate_negative_words+`day of week`, data = ONP_Test)
summary(ONP.lm4)
```







